Less restrictive outgoing mail
onesteinbv/addons-container pull request #130
Opened 2024-02-20 14:07 UTC by tarteo

2024-02-22 09:58 UTC, yung-wang approved these changes
checked with DEV. Code is looking good.

2024-02-22 10:00 UTC, ByteMeAsap commented on mass_mailing_force_dedicated_server/models/mailing_mailing.py
> +            self.env["ir.config_parameter"]
Can you please store the ir.config_parameter object in a variable and use the variable everywhere in the function

2024-02-22 10:00 UTC, ByteMeAsap commented on mass_mailing_force_dedicated_server/tests/test_dedicated_server_check.py
> +        self.env["ir.config_parameter"].set_param(
Can you please store the ir.config_parameter object in a variable and use the variable everywhere in the function

2024-02-22 10:00 UTC, ByteMeAsap commented on mass_mailing_force_dedicated_server/tests/test_dedicated_server_check.py
> +        self.env["ir.config_parameter"].set_param(
Can you please store the ir.config_parameter object in a variable and use the variable everywhere in the function

2024-02-22 10:00 UTC, ByteMeAsap commented on scripts/setup_incoming_mail.py
> +    fetchmail_server = env["fetchmail.server"].search([("private", "=", True)])
Can you please store the fetchmail.server object in a variable and use the variable everywhere in the function

2024-02-22 10:00 UTC, ByteMeAsap commented on scripts/setup_incoming_mail.py
> +    env["ir.config_parameter"].set_param(
Can you please store the ir.config_parameter object in a variable and use the variable everywhere in the function

2024-02-22 10:00 UTC, ByteMeAsap commented on scripts/setup_smtp.py
> +    env["ir.config_parameter"].set_param("mail.default.from", "info")
Can you please store the ir.config_parameter object in a variable and use the variable everywhere in the function

2024-02-22 10:02 UTC, MrGigSolutions requested changes
Very nice, Dennis. Couple of small remarks.

2024-02-22 10:02 UTC, MrGigSolutions commented on mass_mailing_force_dedicated_server/tests/test_dedicated_server_check.py
> +        with self.assertRaises(UserError):
Would you consider using `self.assertRaisesRegex(UserError, "Please configure a dedicated server")`, so you know for certain which UserError is raised?

2024-02-22 10:02 UTC, MrGigSolutions commented on mass_mailing_force_dedicated_server/tests/test_dedicated_server_check.py
> +        with self.assertRaises(UserError):
Same here, but now for the other message.

2024-02-22 10:02 UTC, MrGigSolutions commented on mass_mailing_force_dedicated_server/wizards/mailing_mailing_test.py
> +    def send_mail_test(self):
Would it be better to call `_force_dedicated_server` higher up in the inheritance chain? The fact that you have to override a testing method suggests to me that it would be better to override send, or sudo_send?

2024-02-22 10:11 UTC, tarteo commented on mass_mailing_force_dedicated_server/wizards/mailing_mailing_test.py
> +    def send_mail_test(self):
Ah yes thanks didn't realize mail.mail has a mailing_id :+1:

2024-02-22 13:55 UTC, ByteMeAsap approved these changes

2024-02-27 11:02 UTC, MrGigSolutions approved these changes
Looks good!

2024-02-27 11:21 UTC, merged